# -*- coding: utf-8 -*-
"""ChessEngineCUDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tR1lhIIBa0Gt1CkCW2yOkDL-pp9EFmsU
"""

!nvidia-smi

!apt-get update -y
!apt-get install -y cmake g++ build-essential

!nvcc --version

!git clone -b gpu-v1 https://github.com/NilAysa/ChessEngine.git

# Commented out IPython magic to ensure Python compatibility.
# %cd ChessEngine

!rm -rf build
!cmake -S . -B build -DUSE_CUDA_NNUE=ON

!cmake --build build -j

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# printf "uci\nisready\nucinewgame\nposition startpos\ngo depth 1\nquit\n" | ./build/chess_sophia